### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by medoyounis** [mahdiyousofun/AED-algorithm#2]
when running the code, I get the following error. I have updated the path to the functions and data, but the error still here
 A dynamic link library (DLL) initialization routine failed.

Error in EMAP_xdk (line 182)
        AP = attribute_profile(PC_int16, VectorAttributes(j), Lambda);

Error in morph_detect (line 7)
x=EMAP_xdk(f0,'',false, '', 'a', para); %f0,'',false, '', 'a', para

Error in demo (line 32)
d0 = morph_detect(f0, para, type);

**Comment by wangk98** [comment]
I get the same error! Do you solve it?

**Comment by medoyounis** [comment]
I have solved this issue by installing another version of matlab. The one I have used was R2017b
